Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.disk :disk, size: "200GB", primary: true
  config.vm.boot_timeout = 600

  config.vm.provider "hyperv"
  config.vm.provider "virtualbox"

  config.vm.provider :hyperv do |h|
    h.maxmemory = 24576
    h.memory = 8192
    h.cpus = 4
  end

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 16384
    v.cpus = 4
    v.customize ["modifyvm", :id, "--vram", "128"]
  end
  
  config.vm.provision "basic-root-operation", type: "shell", privileged: true, inline: <<-SHELL
    export LOCAL_USER=localusertochange
    apt-get update -y
    apt-get upgrade -y
    apt-get install -y --no-install-recommends \
      git build-essential sudo openssl \
      parted cloud-guest-utils \
      apt-transport-https ca-certificates curl \
      gnupg  dirmngr lsb-release
    id $LOCAL_USER || useradd -m -G sudo -s /bin/bash $LOCAL_USER
    usermod -p $(openssl passwd -1 -salt 5RPVAd $LOCAL_USER) $LOCAL_USER
    echo "$LOCAL_USER ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$LOCAL_USER"
    ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
    update-locale "LANG=fr_FR.UTF-8"
    locale-gen --purge "fr_FR.UTF-8"
    dpkg-reconfigure --frontend noninteractive locales
  SHELL

  config.vm.provision "grow-partition", type: "shell", privileged: true, inline: <<-SHELL
    growpart /dev/sda 1
    resize2fs /dev/sda1
    df -h /dev/sda1
  SHELL
  
  config.vm.provision "install-all-package", type: "shell", privileged: false, inline: <<-SHELL
    export LOCAL_USER=localusertochange
    sudo install -m 0755 -d /etc/apt/keyrings
    #####
    # Add Google Chrome repository
    #####
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo tee /etc/apt/trusted.gpg.d/google.asc >/dev/null
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/google.gpg >/dev/null
    sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google.list'
    #####
    # Add Firefox repository
    #####
    wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list
    echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo tee /etc/apt/preferences.d/mozilla
    sudo snap remove firefox
    sudo apt-get remove firefox
    #####
    # Add VSCode repository
    #####
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
    rm -f packages.microsoft.gpg
    #####
    # Add Docker repository
    #####
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
$(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    #####
    # Add Pritunl repository
    #####
    echo "deb https://repo.pritunl.com/stable/apt bookworm main" | sudo tee /etc/apt/sources.list.d/pritunl.list
    gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
    gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A | sudo tee /etc/apt/trusted.gpg.d/pritunl.asc
    #####
    # Install Virtualbox guest addition
    #####
    echo "deb http://deb.debian.org/debian $(lsb_release -cs)-backports main contrib" | sudo tee /etc/apt/sources.list.d/backports.list
    sudo apt-get install -y --no-install-recommends fasttrack-archive-keyring
    echo "deb http://fasttrack.debian.net/debian-fasttrack/ $(lsb_release -cs)-fasttrack main contrib" | sudo tee /etc/apt/sources.list.d/fasttrack.list
    echo "deb http://fasttrack.debian.net/debian-fasttrack/ $(lsb_release -cs)-backports-staging main contrib" | sudo tee -a /etc/apt/sources.list.d/fasttrack.list
    #####
    # Install all packages
    #####
    sudo apt-get update -y
    sudo apt-get install -y --no-install-recommends \
      virtualbox-guest-x11 \
      task-gnome-desktop \
      google-chrome-stable google-chrome-beta \
      firefox firefox-l10n-fr \
      code \
      docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
      pritunl-client-electron
    sudo usermod -aG docker $LOCAL_USER
    sudo usermod -aG video $LOCAL_USER
  SHELL

end
